export const ACTIONS = {
  ADD_NEW_TODO: "ADD_NEW_TODO",
  EDIT_TODO: "EDIT_TODO",
  DELETE_TODO: "DELETE_TODO",
  CHECK_AS_COMPLETE: "CHECK_AS_COMPLETE",
  MOVE_UP: "MOVE_UP",
  MOVE_DOWN: "MOVE_DOWN",
};
